// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

declare module "@prismicio/client" {
	namespace Content {
		export type {
			
		}
	}
}